FROM ruby:4.0.2

WORKDIR /app

RUN apt-get update -qq && apt-get install --no-install-recommends -y \
  build-essential git libpq-dev postgresql-client && \
  rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bash", "-lc", "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"]

